### ISSUE TITLE
Can the out buffer be greater than 64 bytes?

### ISSUE THREAD

**Issue by PhillyNJ** [soldernerd/HID_Utility#5]
First, thanks for a really easy to use HID API. I am working on a project where I need to transfer more than 64 bytes. Can the out buffer be greater than 64 bytes?

**Comment by soldernerd** [comment]
Unfortunately it can't. This is not a limitation of the API but of the USB specifications. A HID device can only transmit or receive 64 bytes at a time. But: you can do so every millisecond so maximum throughput is a respectable 64kB per second. So think about splitting your data into smaller chunks and transmitting them one by one.

**Comment by PhillyNJ** [comment]
Thanks for getting back to me so soon. I figured the cap was 64bytes, so plan B is to make several calls.
